# Generated by Django 4.0.4 on 2022-05-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0003_rooms_condition_rooms_count_rooms_empty_rooms_full_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='count',
            new_name='count_s',
        ),
    ]
